apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: ca07d0c6a921acr.azurecr.io/kolor-spring-app:latest
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
        - name: python-service
          image: ca07d0c6a921acr.azurecr.io/kolor-python-service:latest
          ports:
            - containerPort: 5000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: python-service-service
spec:
  selector:
    app: python-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP